# Use mysql:5.7.41 as the base image
# Run docker build -t custom-mysql:5.7.41 --platform linux/amd64 -f Dockerfile-mysql .
FROM mysql:5.7.41

ENV MYSQL_ROOT_PASSWORD=my-secret-pw

# 将SQL脚本添加到镜像中的/docker-entrypoint-initdb.d目录下
COPY init.sql /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init.sql